#!/bin/bash
#SBATCH --job-name=finalproject
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=24gb
#SBATCH --time=24:00:00
#SBATCH --output=/work/gene8940/fae75933/log.%j
#SBATCH --mail-user=fae75933@uga.edu
#SBATCH --mail-type=END,FAIL

OUTDIR="/work/gene8940/fae75933/finalproject"

if [ ! -d $OUTDIR ]
then
    mkdir -p $OUTDIR
fi
cd $OUTDIR

Threads=6
MEMORY=24

wget -O $OUTDIR/GCF_000182925.2_NC12_genomic.fna.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/182/925/GCF_000182925.1_ASM18292v1/GCF_000182925 | gunzip -c > $OUTDIR/GCF_000182925.fna

ml BWA/0.7.17-GCC-8.3.0
bwa index GCF_000182925.fna

ml BWA/0.7.17-GCC-8.3.0
ml SAMtools/1.10-GCC-8.3.0

bwa mem -t 6 GCF_000182925.fna SRR000182925_1.fastq.gz SRR000182925_2.fastq.gz > SRR000182925.sam
samtools view SRR000182925.sam -O BAM -o SRR000182925.bam
