#!/bin/bash
#SBATCH --job-name=Run120code
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=24gb
#SBATCH --time=24:00:00
#SBATCH --output=%j.log.out
#SBATCH --mail-user=fae75933@uga.edu
#SBATCH --mail-type=END,FAIL
#SBATCH --error=%j.log.err


ml BWA/0.7.17-GCC-8.3.0

bwa index /scratch/fae75933/newgenome/GCA_000182925.2_NC12_genomic.fna
